### ISSUE TITLE
Cleverbot error

### ISSUE THREAD

**Issue by Empasm** [Twentysix26/26-Cogs#1]
here is the error i got after installing this cog

[08/06/2016 16:07] ERROR owner load 68: No module named 'cleverbot'
Traceback (most recent call last):
  File "/root/Red-DiscordBot/cogs/owner.py", line 59, in load
    self._load_cog(module)
  File "/root/Red-DiscordBot/cogs/owner.py", line 491, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/Red-DiscordBot/cogs/cleverbot.py", line 1, in <module>
    from cleverbot import Cleverbot as Clv
ImportError: No module named 'cleverbot'

**Comment by Empasm** [comment]
and im stupid, that would be from not having installed cleverbot::: pip3 install cleverbot
