### ISSUE TITLE
[Trigger] Function object is not iterable

### ISSUE THREAD

**Issue by Kowlin** [Twentysix26/26-Cogs#7]
Found this little gem in #support today, enjoy ;)
```Traceback (most recent call last):
  File "C:\Users\Volpe\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "C:\Users\Volpe\Documents\Red Bot\cogs\trigger.py", line 439, in on_message
    if self.is_command(message.content):
  File "C:\Users\Volpe\Documents\Red Bot\cogs\trigger.py", line 407, in is_command
    for p in self.bot.command_prefix:
TypeError: 'function' object is not iterable```

**Comment by Twentysix26** [comment]
User with outdated cog
